24Q2
dariok/wdbplus pull request #558
Opened 2024-06-17 14:23 UTC by dariok

2024-07-02 05:51 UTC, WunschK commented
lgtm

2024-07-02 06:08 UTC, WunschK requested changes
linting-config shared accidentally
wdb0000 without wdbErr should be removed from error.xqm

2024-07-02 06:08 UTC, WunschK commented on edoc/modules/error.xqm
shouldn't "wdb0000" be removed, as "wdbErr:wdb0000" already covers this? (in the new version)

2024-07-02 06:08 UTC, WunschK commented on eslint.config.js
mistake or was your intention to share a linting-config?

2024-07-02 22:05 UTC, dariok commented
- ESLint config: should be helpful to assure using the same standards and checks; this contains no secrets
- Names of errors may be with or without a namespace
- wherever possible, similar errors should have a similar error number

2024-07-04 11:26 UTC, WunschK approved these changes

2024-07-04 11:26 UTC, merged